server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: usian-cart-service
  redis:
    cluster:
      nodes:
        - 192.168.205.129:7001
        - 192.168.205.129:7002
        - 192.168.205.129:7003
        - 192.168.205.129:7004
        - 192.168.205.129:7005
        - 192.168.205.129:7006
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接

#购物车
CART_REDIS_KEY: CART_REDIS_KEY